name: el-kiosco
region: nyc
features:
  - buildpack-stack=ubuntu-22

static_sites:
  - name: web
    # 👇 CAMBIAR por tu usuario/repo de GitHub antes de crear la app
    github:
      repo: TU-USUARIO/el-kiosco
      branch: main
      deploy_on_push: true
    source_dir: /
    # No hay build: es HTML plano. Se sirve el directorio tal cual.
    output_dir: /
    index_document: index.html
    error_document: index.html
    catchall_document: index.html
